name: flutter0322
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #wilt: "^3.4.1"
  #wilt: any
  tuple: "^1.0.1"
  color: "^2.0.2"
  #mqtt_client: "^1.7.1"
  mqtt_client: 
      path: /Users/cwitte/scratch/mqtt_client
  archive: "^1.0.33"
  path: "^1.5.1"
  #protobuf: ">=0.3.4 <0.4.0"
  #dson: "any"
  intl: "^0.15.6"

  semaphore: "^0.0.1"
  sqflite: "^0.8.9"

  #path_provider: "^0.4.0"
  cupertino_icons: "^0.1.0"
  json_object: "^1.0.19"
  xml: "^3.0.0"
  cached_network_image: "^0.4.1+1"
  pubsub: "^1.1.9"

  #wilt:
  #   path: /Users/cwitte/scratch/wilt
  #wilt:
  #  git: https://github.com/shamblett/wilt.git

  #dartson: "^0.2.7"
  #firebase_auth: "^0.2.3"
  #google_sign_in: "^0.3.1"

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/finish_flag_128.9.png
   - images/finish_flag.png
   - images/chicago_aasbd.9.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
